---
title: "Movie Dialogue Analysis"
output: html_document
runtime: shiny
margin: 2cm
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r echo=FALSE, include=FALSE}

library(dplyr)
library(ggplot2)
library(stringr)
library(shinyWidgets)
library(plotly)
library("shinydashboard")
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")


file_list <- list.files("filmScripts/")

for (file in file_list){
  #print(file)
  # if the merged dataset doesn't exist, create it
  if (!exists("dataset")){
    dataset <- readxl::read_xlsx(paste0("filmScripts/",file))
    dataset$Movie = str_remove_all(file,".xlsx")
    names(dataset) = c("Character","Dialogue","Song","Movie")
  }
  
  # if the merged dataset does exist, append to it
  if (exists("dataset")){
    temp_dataset <-readxl::read_xlsx(paste0("filmScripts/",file))
    temp_dataset$Movie = str_remove_all(file,".xlsx")
    names(temp_dataset) = c("Character","Dialogue","Song","Movie")
    #print("past")
    dataset<-rbind(dataset, temp_dataset)
    rm(temp_dataset)
  }
  
}

dataset$Movie = factor(dataset$Movie)
dataset = dataset[is.na(dataset$Song),]

movieTitles = list('Solo Films' = list("Kabhi Khushi Kabhie Gham 2001","Sholay 1975","Shree 420 1955"), 
                   'Mission Impossible Series' = list("Mission Impossible 1996", "Mission Impossible 2 2000", "Mission Impossible 3 2006","Mission Impossible Rogue Nation 2015","Mission Impossible Ghost Protocol 2011"),
                   'Dirty Harry Series' = list("Dirty Harry 1 1971","Dirty Harry 2 Magnum Force 1973","Dirty Harry 3 The Enforcer 1976","Dirty Harry 4 Sudden Impact 1983","Dirty Harry 5 The Dead Pool 1988"),
                   'Bond films' = list("From Russia With Love 1963","The World Is Not Enough 1999")
)

GenerateWordCounts = function(dataframe_in){
  length_of_df = nrow(dataframe_in)
  word_counts = rep(NA,length_of_df)
  for(i in 1:length_of_df){
    numWords = length(unlist(strsplit(dataframe_in$Dialogue[i]," ")))
    word_counts[i] = numWords
  }
  return(word_counts)
}

dataset$'WordCount' = GenerateWordCounts(dataset)

dataset_aggregated = dataset[,c('Character','Movie')]

dataset_aggregated$WordCount = ave(dataset$WordCount,dataset_aggregated,FUN=sum)


dataset_aggregated = dataset_aggregated[!duplicated(dataset_aggregated),]

generate_plotly = function(df){
  
  size_of_df = nrow(df)
  plot = ggplot(df, aes(x =  Character, y = WordCount,fill = Movie))+
    geom_bar(stat="identity", position = position_dodge(width = 0.8),width = 0.5)+
    coord_flip()+
    theme(legend.position = "right")+
    ggtitle("Words Spoken by each Character")
  return(ggplotly(plot, height = size_of_df*15,width = 800))
}

#this will be used for the word Cloud
Movies = unlist(movieTitles)
length_of_movie_list = length(Movies)
script_list = list()

for(i in 1:length_of_movie_list){
  script_list[Movies[i]] = paste(dataset[dataset$Movie==Movies[i],"Dialogue"], collapse = "")
}
generate_word_cloud = function(script){
  working_script = Corpus(VectorSource(script))
  #inspect(working_script)
  working_script <- tm_map(working_script, content_transformer(tolower))
  
  # Remove numbers
  working_script <- tm_map(working_script, removeNumbers)
  # Remove english common stopwords
  working_script <- tm_map(working_script, removeWords, stopwords("english"))
  # Remove your own stop word
  # specify your stopwords as a character vector
  
  # Remove punctuations
  working_script <- tm_map(working_script, removePunctuation)
  # Eliminate extra white spaces
  working_script <- tm_map(working_script, stripWhitespace)
  # Text stemming
  # working_script <- tm_map(working_script, stemDocument)
  
  dtm <- TermDocumentMatrix(working_script)
  m <- as.matrix(dtm)
  v <- sort(rowSums(m),decreasing=TRUE)
  d <- data.frame(word = names(v),freq=v)
  set.seed(1234)
  wordcloud(words = d$word, freq = d$freq, min.freq = 1,
            max.words=50, random.order=FALSE, rot.per=0.35, 
            colors=brewer.pal(8, "Dark2"))
}


```


```{r app, echo=FALSE, message=FALSE}

#packages used in the app
library(shiny)

#library(DT)



shinyApp(
  ui = fluidPage(
    titlePanel("Dialogue in Cinema"),
    sidebarPanel(
      uiOutput("var1_select"),
      actionButton(inputId = "update",                   
                   label = "Render Graph"
      )
    ),mainPanel(
      tabsetPanel(type = "tabs",
                  tabPanel("Plot", plotlyOutput("plot")),
                  tabPanel("Word Cloud", plotOutput("wordCloud", height = 600, width = 600))
                  )

      
    )
    
  ),
  server = function(input, output) {
    
    output$var1_select <- renderUI({#add multiple = TRUE to include multiple movies
      selectInput("variable", "Movie",choices = movieTitles, selected = "Mission Impossible 1996")
      
    })
    
    active_dataset = 
      eventReactive(input$update, { # Event Reactive
        dataset_aggregated[dataset_aggregated$Movie %in% input$variable,]
      })
    
    output$data <- renderTable(
      active_dataset()
    )
    
    output$plot <- renderPlotly(
      generate_plotly(active_dataset())
    )
    
    output$wordCloud = renderPlot(
      generate_word_cloud(script_list[[input$variable]])
    )
    
  },
  options = list(width = 1300,height = 800)
)




```
